# Generated by Django 4.0.6 on 2022-07-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], default='ML', max_length=2),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('LT', 'Lost'), ('FD', 'Found')], default='LT', max_length=2),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('DG', 'Dog'), ('CT', 'Cat'), ('OT', 'Other')], default='DG', max_length=2),
        ),
    ]
