# Generated by Django 4.0.6 on 2022-07-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_pet_options_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='https://sugarplumnannies.com/wp-content/uploads/2015/11/dog-placeholder.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], default='LOST', max_length=5),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('PET', 'Other')], default='DOG', max_length=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pet'),
        ),
    ]
