# Generated by Django 4.0.6 on 2022-07-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_member_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/images/profile-image.png', null=True, upload_to=''),
        ),
    ]
